name: Azure Terraform Deployment
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-azure@v3
        with:
          azure-credential-file: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Initialize Terraform
        run: terraform init
      - name: Plan Terraform
        run: terraform plan
      - name: Apply Terraform
        run: terraform apply -auto-approve